### ISSUE TITLE
this is shit bro

### ISSUE THREAD

**Issue by iiEthan** [MarioFoli/InfiniteChestsV3#1]
make it better

**Comment by muzak23** [comment]
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠴⠒⠛⠉⠙⠳⡄⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⢠⣴⣾⣿⣷⣦⣄⠀⠀⠀⡤⠟⠚⠛⠛⠓⡆⠀⢷⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⢀⣿⣿⣿⠿⠟⠛⠛⠳⣄⠸⣇⡀⠀⣀⣀⣰⡇⠀⢸⠓⢲⡀⠀
⠀⠀⠀⠀⢠⣶⣾⣿⣿⣿⣷⣦⣤⣤⣤⣼⠆⡟⠻⠿⠿⠿⠟⠁⠀⢸⡇⢰⡇⠀
⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⡇⠀⠀⠀⠀⠀⠀⠀⢸⡇⢸⠇⠀
⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⣇⠀⠀⠀⠀⠀⠀⠀⠈⣧⣸⠀⠀
⠀⠀⠀⠀⠸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠇⠀⢻⠀⢀⣀⣀⣴⠀⠀⠀⢹⠅⠀⠀
⠀⠀⠀⢀⡀⠀⣾⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⡏⠀⠀⢸⡇⣿⠀⠀⠀⢸⠀⠀⠀
⠀⠀⣠⣼⣿⣦⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⠀⡇⠀⠀⢸⡇⣿⠀⠀⠀⣼⠀⠀⠀
⢠⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠀⣿⠀⠀⢸⡇⢸⠀⠀⠀⡿⠀⠀⠀
⠈⠉⠁⠉⠻⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⢿⠀⠀⣸⠁⢸⠀⠀⠀⡇⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠉⠛⠿⣿⣿⣿⣿⡿⠟⠀⠀⢸⡄⠀⣯⠀⣸⠀⠀⢰⡇⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⣿⣿⣿⠀⠀⠀⠀⠀⢯⠀⠘⡇⢹⡆⠀⠸⡇⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⢀⣾⣿⣿⡿⠃⠀⠀⠀⠀⠀⢸⠀⢠⡇⢸⡇⠀⢰⠇⠀⠀⠀
⠀⠀⠀⠀⠀⠀⣰⣿⣿⡿⠋⠀⠀⠀⠀⠀⠀⠀⢸⠀⣼⠀⠀⡇⠀⣼⠀⠀⠀⠀
⠀⠀⠀⠀⠀⢰⣿⣿⣿⡄⠀⠀⠀⠀⠀⠀⢶⣯⣭⠤⠿⣠⣖⣃⣀⣹⡄⠀⠀⠀
⠀⠀⠀⠀⠀⠘⠿⠹⠿⢿⠆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠉⠉⠉⠉⠀⠀⠀⠀

**Comment by 5space** [comment]
TRUE rthis sucks please fix it

**Comment by RayshenOmega** [comment]
it works as intended now atleast for me.

**Comment by iiEthan** [comment]
> it works as intended now atleast for me.

Do 👂 u 👈 suppowt 🤗 gays 🏳️‍🌈 and wesbians? like 🌸 da peopwe 👥 who 🤷 awe in 👇👏 da lgbt 👩‍👩‍👦 community? 💰 aftew 😡 a quick 🏃 pause, ⏯ me 🤢 gave 🎁 hew 👩 my 😘 wepwy: no. 😣😣

**Comment by RenderBr** [comment]
https://github.com/RenderBr/Supplier

**Comment by ryouzue** [comment]
> https://github.com/RenderBr/Supplier

It lacks every other functionality this plugin does, thus only reason I'm using this plugin is for the ability to lock chests & allow other users to open them and that's it, along with other options that come along with it.

After using the updated version for latest TShock, apparently there is this issue with this plugin where on PC works as intended but on any other devices such as Mobile/iPad you cant, the issue itself is that you can manage to put a new chest and have it claimed but the moment you rejoin, you can't open it anymore even if it's claimed by you.

**Comment by RenderBr** [comment]
> > https://github.com/RenderBr/Supplier
> 
> It lacks every other functionality this plugin does, thus only reason I'm using this plugin is for the ability to lock chests & allow other users to open them and that's it, along with other options that come along with it.
> 
> After using the updated version for latest TShock, apparently there is this issue with this plugin where on PC works as intended but on any other devices such as Mobile/iPad you cant, the issue itself is that you can manage to put a new chest and have it claimed but the moment you rejoin, you can't open it anymore even if it's claimed by you.

That's a valid statement. Supplier doesn't allow locking or claiming of chests, but functionally it works a lot better. Supplier is primarily intended for free items servers, but I figure that's what most people using this plugin want anyway, as the name suggests. "InfiniteChests"

**Comment by ryouzue** [comment]
> That's a valid statement. Supplier doesn't allow locking or claiming of chests, but functionally it works a lot better. Supplier is primarily intended for free items servers, but I figure that's what most people using this plugin want anyway, as the name suggests. "InfiniteChests"

Do you perhaps happen to know any "working" plugin that has the features I'm looking for?
I've checked your repository full of useful plugins, that's apparently where I got the InfiniteChestV3 from
